import avatarImages from "../../../assets/images";
const navbarDropdownItemsData = [
  {
    id: 1,
    avatarAlt: "audio",
    avatarSrc: avatarImages.audioImage,
    itemName: "Audio",
    linkAddPath: "/app/audio/add",
    linkTablePath: "/app/audio",
  },
  {
    id: 2,
    avatarAlt: "časopisi",
    avatarSrc: avatarImages.magazinesImage,
    itemName: "Časopisi",
    linkAddPath: "/app/magazines/add",
    linkTablePath: "/app/magazines",
  },
  {
    id: 3,
    avatarAlt: "dokumenti",
    avatarSrc: avatarImages.documentsImage,
    itemName: "Dokumenti",
    linkAddPath: "/app/documents/add",
    linkTablePath: "/app/documents",
  },
  {
    id: 4,
    avatarAlt: "Film i Video",
    avatarSrc: avatarImages.videoImage,
    itemName: "Film i Video",
    linkAddPath: "/app/video/add",
    linkTablePath: "/app/video",
  },
  {
    id: 5,
    avatarAlt: "Fotografske Zbirke",
    avatarSrc: avatarImages.photosImage,
    itemName: "Fotografske Zbirke",
    linkAddPath: "/app/photo_collections/add",
    linkTablePath: "/app/photo_collections",
  },
  {
    id: 6,
    avatarAlt: "knjige",
    avatarSrc: avatarImages.booksImage,
    itemName: "Knjige",
    linkAddPath: "/app/books/add",
    linkTablePath: "/app/books",
  },
  {
    id: 7,
    avatarAlt: "novine",
    avatarSrc: avatarImages.newspapersImage,
    itemName: "Novine",
    linkAddPath: "/app/newspapers/add",
    linkTablePath: "/app/newspapers",
  },
  {
    id: 8,
    avatarAlt: "plakati",
    avatarSrc: avatarImages.postersImage,
    itemName: "Plakati",
    linkAddPath: "/app/posters/add",
    linkTablePath: "/app/posters",
  },
  {
    id: 9,
    avatarAlt: "Postanske Markice",
    avatarSrc: avatarImages.stampsImage,
    itemName: "Poštanske Markice",
    linkAddPath: "/app/stamps/add",
    linkTablePath: "/app/stamps",
  },
  {
    id: 10,
    avatarAlt: "razglednice",
    avatarSrc: avatarImages.postcardsImage,
    itemName: "Razglednice",
    linkAddPath: "/app/postcards/add",
    linkTablePath: "/app/postcards",
  },
];

export default navbarDropdownItemsData;
